### ISSUE TITLE
Listener for previous and next month

### ISSUE THREAD

**Issue by jimmyale3102** [hi-manshu/Kalendar#106]
Hi there Kalendar Team!!
First of all I wanna say Congrats and thanks for this incredible library. 

I Implemented it on my personal project and it works great. However there is a feature that I'd like you to add. I'm talking about the onPreviousClick and onNextClick on KalendarHeader. I'd like to know when user clicks on those options. You could return a lambda to let us to handle the logic.

Thanks in advance guys!

**Comment by hi-manshu** [comment]
Hey buddy, I am about to add a new design version for it and there you can add your own custom design as you like

**Comment by hi-manshu** [comment]
Hey mind checking 
https://github.com/hi-manshu/Kalendar/releases/tag/v1.3.0
It has options to add own custom Header/ Please do check

**Comment by jimmyale3102** [comment]
Hey!... I'll check it. Thanks
