### ISSUE TITLE
Support swiping to change dates

### ISSUE THREAD

**Issue by Rafsanjani** [hi-manshu/Kalendar#127]
As a user, I would find it really convenient if I could swipe either left/right on the calendar to change the selected date.

**Comment by hi-manshu** [comment]
Hey i have fixed it, and released it version 1.3.1
Need to update the documentation

**Comment by hi-manshu** [comment]
@Rafsanjani there you go:
https://github.com/hi-manshu/Kalendar/releases/tag/1.3.1
