### ISSUE TITLE
Fonts ratio breaks UI

### ISSUE THREAD

**Issue by aldefy** [hi-manshu/Kalendar#14]
If the phone settings is set to large or enhanced to 2x..3x etc 
the UI breaks :
![screen-1642746396](https://user-images.githubusercontent.com/1392571/150512455-961f834a-f1a3-4043-9794-8819314291c7.png)

**Comment by gsrathoreniks** [comment]
@hi-manshu how this can be handled?

**Comment by hi-manshu** [comment]
It should be f

**Comment by gsrathoreniks** [comment]
@hi-manshu Yes, it's fixed.
