### ISSUE TITLE
Allow customization of initial day of week

### ISSUE THREAD

**Issue by carstenhag** [hi-manshu/Kalendar#15]
In Germany, Spain and I guess many other European countries, the week starts with Monday, not Sunday.

In any case, it would be great to have an option to have this done automatically/manually set locale/manually set the first weekday.

**Comment by hi-manshu** [comment]
Oh sure, this seems to be a good Idea. I will definitely be working on this. Thanks for suggestion.

**Comment by jeluchu** [comment]
@carstenhag, I have created a Pull Request (#37) in which I include this customization parameter inside KalendarKonfig, I have tested it and it works, it is currently pending of revision 😄

**Comment by gsrathoreniks** [comment]
@hi-manshu This can be closed! fixed with #38
