### ISSUE TITLE
Add the possibility to choose the language of the calendar.

### ISSUE THREAD

**Issue by YvesKalume** [hi-manshu/Kalendar#16]
Thanks for this library ! it's very useful, I'm using it in one of my applications, it works well but the problem is that the language of days and months is only English.

It would be great if we could choose the language for example in the constructor of `kalendarConfig`.

I tried to implement this feature and it works if possible I can open a PR.

Thanks !

**Comment by hi-manshu** [comment]
Hey, thanks for the review. If you have already implemented please feel free to open a PR. Or else I will try to do it in near future.

**Comment by hi-manshu** [comment]
Hey @YvesKalume ,
You can check the requested feature here : https://github.com/hi-manshu/Kalendar/pull/22

I hope this is what you were looking for!

**Comment by YvesKalume** [comment]
@hi-manshu yes that's right

**Comment by yahyaizala** [comment]
It does not support Turkish yet.
Hi there, how can I extend Local'e to Turkish ?
thanks.

**Comment by nikolasguillen** [comment]
Locale is not working in 1.3.2, in fact the list of months is a simple enum
`private val WeekDays = listOf("M", "T", "W", "T", "F", "S", "S")`

Am I missing something?
