### ISSUE TITLE
Date range picker would be a nice add.

### ISSUE THREAD

**Issue by imnithish** [hi-manshu/Kalendar#26]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hi-manshu** [comment]
@imnithish can you add more context in the description?

**Comment by marcogian2001** [comment]
hi, I would need this feature too, in practice on the Kalendar Firey, it would be useful if by clicking the first time on a day the kalendar selects you the first day, then clicking on another day the kalendar selects you the whole range of days from the start day to the last. Thanks

**Comment by molpoo** [comment]
Hello, sadly, this issue doesn't get any more traction since 6 months. 
Is it still planned on your side ?

@gsrathoreniks do you have ideas to implement this ?

**Comment by hi-manshu** [comment]
Hey buddy,
Will be picking this up in November first week as have been busy with
conferences.
And sorry for the delay!

**Comment by hi-manshu** [comment]
Hey added in v1.3.0

**Comment by hi-manshu** [comment]
@molpoo @marcogian2001 added it folks!
