### ISSUE TITLE
Create apk in github assets

### ISSUE THREAD

**Issue by yogeshpaliyal** [hi-manshu/Kalendar#27]
It would be very good to add apk in github action assets on each release, so developers can get a hands on experience on library, without implementing on their project or importing this project

**Comment by hi-manshu** [comment]
Thats a good suggestion, Will do thanks!

**Comment by yogeshpaliyal** [comment]
Can I work on this? @hi-manshu

**Comment by hi-manshu** [comment]
Yes pelase @yogeshpaliyal
