### ISSUE TITLE
Multiple Events to be returned on day click

### ISSUE THREAD

**Issue by rohansaigaonkar** [hi-manshu/Kalendar#30]
**Is your feature request related to a problem? Please describe.**
When a day is clicked, and an event is returned, if there are multiple events, we only get the first event on that day. 

**Describe the solution you'd like**
Returns a list of all events on that day

**Comment by hi-manshu** [comment]
Thats a good idea. let me add this as potential event feature. Thank you for suggestion @rohansaigaonkar
