### ISSUE TITLE
date range selection 

### ISSUE THREAD

**Issue by taymiyyah** [hi-manshu/Kalendar#39]
**Is your feature request related to a problem? Please describe.**
as a user I would like to select day from- to  and see all days in blue color, to select trip date range 
<img width="365" alt="image" src="https://user-images.githubusercontent.com/81846446/167851053-5bc93400-e159-4306-aea3-165264f4f45e.png">

**Comment by hi-manshu** [comment]
Hey He!
THere is an option to add it now!
