### ISSUE TITLE
Scrolling is not smooth

### ISSUE THREAD

**Issue by AniruddhaKulk** [hi-manshu/Kalendar#42]
**Describe the bug**
Try scrolling through the months and it's not smooth. 

**To Reproduce**
Just scroll through the months and we can see the lag. 

**Expected behavior**
Can we make scrolling smooth to improve the user experience?

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hi-manshu** [comment]
Can you check now, I have added the LazyColumn.

Fixed with https://github.com/hi-manshu/Kalendar/releases/tag/v1.1.0_v1.0.0-Release
