### ISSUE TITLE
Include an event mark on days

### ISSUE THREAD

**Issue by Jeluchu** [hi-manshu/Kalendar#5]
Hi, first of all thank you very much for developing a calendar in Compose as there is no calendar component as with XML.

On the other hand, from what I have seen it doesn't seem to me that you have that included but I comment it to you in case you are planning to develop it or in case it is there and I haven't noticed it.

The idea is that when you pass a series of lists with dates (month and day) in the calendar it appears marked with a dot or in some way as that day there is an event or something, then if you click on that day it shows what the developer wants (which as such if I have seen that you have put that if you click on a day it shows what the developer wants).

I don't know what you think, tell me whatever it is, and of course, thank you very much

**Comment by hi-manshu** [comment]
Hey @Jeluchu,
Added the requested feature and closing this now. Show your love by sharing and helping us spread the word.

Thanks
