### ISSUE TITLE
Jank in Endloss scroll

### ISSUE THREAD

**Issue by yogeshpaliyal** [hi-manshu/Kalendar#54]
**Describe the bug**
Seeing a jank on scroll.

**Device**
Model : Redmi note 10 pro max
OS : Android 12

**Screenshots**
https://user-images.githubusercontent.com/9381846/185351273-649269d4-7655-478e-b16b-9cbc19a741c0.mp4

**Comment by hi-manshu** [comment]
Redid from 0, please check
