### ISSUE TITLE
Events dots visible for all dates.

### ISSUE THREAD

**Issue by gsrathoreniks** [hi-manshu/Kalendar#55]
**Describe the bug**
Even if the event is set for a specific date, it's showing events on all the dates throughout the calendar, 

**To Reproduce**
1. Add events
2. See the preview in device

**Comment by lrnbrad** [comment]
I think it's KalendarDay.kt's problem, maybe can check the LocalTime and events before placing the dot?

like:
```kotlin
if (kalendarEvents.isNotEmpty()) {
    kalendarEvents.forEachIndexed { index, event ->
        if(event.date == kalendarDay) {
            KalendarDots(
                modifier = Modifier,
                index = index,
                size = size,
                color = dotColor
                )
            }
        }
    }
```

**Comment by hi-manshu** [comment]
This will be fixed in today's release
