### ISSUE TITLE
I'd like to feature your library on JetpackCompose.app

### ISSUE THREAD

**Issue by vinaygaba** [hi-manshu/Kalendar#58]
Hey! I'd like to feature your library on [JetpackCompose.app/ComposeCatalog](https://www.jetpackcompose.app/compose-catalog). Just wanted to give you a heads up!

**Comment by hi-manshu** [comment]
Hey that would be great @vinaygaba! Thank you for considering

**Comment by vinaygaba** [comment]
@hi-manshu Sorry about not having done that long ago. I completely missed it and got reminded on Twitter over the last couple days.

**Comment by hi-manshu** [comment]
Please don't be sorry, thanks for considering
