### ISSUE TITLE
Kalendar Firey: Year doesn't change

### ISSUE THREAD

**Issue by SapuSeven** [hi-manshu/Kalendar#78]
**Describe the bug**
The year always stays the same.

**To Reproduce**
1. Create a basic Kalendar Firey instance: `Kalendar(kalendarType = KalendarType.Firey)`
2. Click on the "next month" button until you cross a year boundary (e.g. "December" > "January")
3. The year stays the same and the calendar just loops the initial year

**Expected behavior**
The year should increase/decrease when crossing year boundaries.

**Comment by hi-manshu** [comment]
Hey, this will be fixed in the new release
