### ISSUE TITLE
Oceanic View - add day of week above date

### ISSUE THREAD

**Issue by mhaynesjr** [hi-manshu/Kalendar#79]
Currently the Oceanic view shows the week view of the Kalendar. There is no indication of what day of the week it is like in the Fiery view ( M T W T F S S )

Perhaps as an option? Show/Hide the Day of the week letters above the date? Example
M T W T F S S
1  2  3  4 5 6 7

**Comment by hi-manshu** [comment]
Hey buddy, I have released an option to hide/show the weeks. Can you check! Thanks
