### ISSUE TITLE
KalendarDay's textSize, text style and Shape are not customizable

### ISSUE THREAD

**Issue by molpoo** [hi-manshu/Kalendar#93]
**Is your feature request related to a problem? Please describe.**
Hello, I am testing this library and I saw that a few things have a default value that can't be customizable.

For example, in the `KalendarDay` composable, the textSize cannot be overridden because the `KalendarFirey` comp that uses `KalendarDay` do not pass a value to the `textSize` parameter.
The shape is also not customizable and is set to CircleShape.
The text style isn't customizable as well.

**Describe the solution you'd like**
A way to pass the textSize, the text style and the shape in the KalendarDay.

**Comment by hi-manshu** [comment]
Hey will add this to enhancement, have few things to change will keep for this as well
